# Setup
title: Sam Krauser
url: "https://samkrauser.com.au"
paginate: 1
baseurl: "samkrauser.com.au"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sam Krauser
  url: https://twitter.com/mdo
  email: sam@samkrauser.com.au

# Custom vars
version: 3.0.0

# Navbar page list
# nav:
#  - title: Movies
#    url: /archive